#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

using namespace std;

int  MDC(int a, int b, double teste ) {
int Retorno;
int k;
int ti_1;
int tb_2;
int ti_3;
int ti_4;
  ti_1 = a % b;
  tb_2 = ti_1 == 0;
  tb_2 = !tb_2;

  if( tb_2 ) goto l_else_1;
  Retorno = b;
  goto l_end_2;
l_else_1:;
  ti_3 = a % b;
  ti_4 = MDC( b, ti_3, 1.0 );
  Retorno = ti_4;
l_end_2:;
 return Retorno;
}

int main() { 
int Retorno;
int i;
int v[4];
int m[5][5];
int n[5][5];
int o[5][5];
int x;
int ti_5;
int tb_6;
int ti_8;
int tb_9;
int ti_10;
int tb_11;
int tb_12;
int tb_13;
int ti_14;
int tb_15;
int tb_16;
int tb_17;
int ti_18;
int tb_19;
int tb_20;
int tb_21;
int ti_22;
int ti_23;
int tb_24;
int tb_25;
int tb_26;
int ti_27;
  i = 0;
  ti_5 = 10;
l_teste_for_3:;
  tb_6 = i > ti_5;
  if( tb_6 ) goto l_fim_for_4;
  cout << i;
  cout << endl;
  i = i + 1;
  goto l_teste_for_3;
l_fim_for_4:;
ti_8 = 20;
l_teste_while_5:;
  tb_9 = i >= ti_8;
  if( tb_9 ) goto l_fim_while_6;
int ti_7;
  cout << i;
  cout << endl;
  ti_7 = i + 1;
  i = ti_7;
  goto l_teste_while_5;
l_fim_while_6:;
  v[0] = 1;
  cout << "1dim";
  cout << endl;
  tb_11 = 0 >= 0;
  tb_12 = 0 <= 4;
  tb_13 = tb_11 && tb_12;
  if( tb_13 ) goto l_limite_array_ok_7;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 4 );
  cout << endl;
  exit( 1 );
  l_limite_array_ok_7:;
  ti_10 = v[0];
  cout << ti_10;
  cout << endl;
  m[0][0] = 1000;
  n[0][0] = 3;
  tb_15 = 0 >= 0;
  tb_16 = 0 <= 5;
  tb_17 = tb_15 && tb_16;
  if( tb_17 ) goto l_limite_array_ok_8;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  tb_15 = 0 >= 0;
  tb_16 = 0 <= 5;
  tb_17 = tb_15 && tb_16;
  if( tb_17 ) goto l_limite_array_ok_8;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  l_limite_array_ok_8:;
  ti_14 = m[0][0];
  tb_19 = 0 >= 0;
  tb_20 = 0 <= 5;
  tb_21 = tb_19 && tb_20;
  if( tb_21 ) goto l_limite_array_ok_9;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  tb_19 = 0 >= 0;
  tb_20 = 0 <= 5;
  tb_21 = tb_19 && tb_20;
  if( tb_21 ) goto l_limite_array_ok_9;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  l_limite_array_ok_9:;
  ti_18 = n[0][0];
  ti_22 = ti_14 * ti_18;
  o[0][0] = ti_22;
  cout << "2dim";
  cout << endl;
  tb_24 = 0 >= 0;
  tb_25 = 0 <= 5;
  tb_26 = tb_24 && tb_25;
  if( tb_26 ) goto l_limite_array_ok_10;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  tb_24 = 0 >= 0;
  tb_25 = 0 <= 5;
  tb_26 = tb_24 && tb_25;
  if( tb_26 ) goto l_limite_array_ok_10;
    printf( "Limite de array ultrapassado: %d <= %d <= %d", 0 ,0, 5 );
  cout << endl;
  exit( 1 );
  l_limite_array_ok_10:;
  ti_23 = o[0][0];
  cout << ti_23;
  cout << endl;
 cout << "Escreva:";
 cin >> i;
  cout << i;
  cout << endl;
  ti_27 = MDC( 40, 32, 1.0 );
  cout << ti_27;
  cout << endl;
}

