#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from trabalho.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "trabalho.y"

#include <string>
#include <iostream>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <map>

using namespace std;

int yylex();
void yyerror( const char* st );
void erro( string msg );

// Faz o mapeamento dos tipos dos operadores
map< string, string > tipo_opr;

// Pilha de variáveis temporárias para cada bloco
vector< string > var_temp;

#define MAX_DIM 2 

enum TIPO { FUNCAO = -1, BASICO = 0, VETOR = 1, MATRIZ = 2 };

struct Tipo {
  string tipo_base;
  TIPO ndim;
  int tamanho1[MAX_DIM];
  int tamanho2[MAX_DIM];
  vector<Tipo> retorno; // usando vector por dois motivos:
  // 1) Para não usar ponteiros
  // 2) Para ser genérico. Algumas linguagens permitem mais de um valor
  //    de retorno.
  vector<Tipo> params;
  
  Tipo() {} // Construtor Vazio
  
  Tipo( string tipo ) {
    tipo_base = tipo;
    ndim = BASICO;
  }
  
  Tipo( string base, int tamanho ) {
    tipo_base = base;
    ndim = VETOR;
    this->tamanho1[0]=tamanho;
  }
  
  Tipo( string base, int tamanho1, int tamanho2  ) {
    tipo_base = base;
    ndim = MATRIZ;
    this->tamanho1[0] = tamanho1;
    this->tamanho2[0] = tamanho2;
  }
  
  Tipo( Tipo retorno, vector<Tipo> params ) {
    ndim = FUNCAO;
    this->retorno.push_back( retorno );
    this->params = params;
  } 
};

struct Atributos {
  string v, c; // Valor, tipo e código gerado.
  Tipo t;
  vector<string> lista_str; // Uma lista auxiliar de strings.
  vector<Tipo> lista_tipo; // Uma lista auxiliar de tipos.
  
  Atributos() {} // Constutor vazio
  Atributos( string valor ) {
    v = valor;
  }

  Atributos( string valor, Tipo tipo ) {
    v = valor;
    t = tipo;
  }
};

// Declarar todas as funções que serão usadas.
void insere_var_ts( string nome_var, Tipo tipo );
void insere_funcao_ts( string nome_func, Tipo retorno, vector<Tipo> params );
Tipo consulta_ts( string nome_var );
string declara_variavel( string nome, Tipo tipo );
string declara_funcao( string nome, Tipo retorno, 
                       vector<string> nomes, vector<Tipo> tipos );

void empilha_ts();
void desempilha_ts();

string gera_nome_var_temp( string tipo );
string gera_label( string tipo );
string gera_teste_limite_array( string indice_1, Tipo tipoArray );
string gera_teste_limite_array( string indice_1, string indice_2, 
                                Tipo tipoArray );
int verifica_tipo(Tipo var1, string var2);
void debug( string producao, Atributos atr );
int toInt( string valor );
string toString( int n );

Atributos gera_codigo_operador( Atributos s1, string opr, Atributos s3 );
Atributos gera_codigo_if( Atributos expr, string cmd_then, string cmd_else );

string traduz_nome_tipo_pascal( string tipo_pascal );

string includes = 
"#include <iostream>\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"\n"
"using namespace std;\n";


#define YYSTYPE Atributos


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	TK_ID	258
#define	TK_CINT	259
#define	TK_CDOUBLE	260
#define	TK_VAR	261
#define	TK_PROGRAM	262
#define	TK_BEGIN	263
#define	TK_END	264
#define	TK_MAININ	265
#define	TK_MAINFIM	266
#define	TK_ATRIB	267
#define	TK_WRITELN	268
#define	TK_READ	269
#define	TK_CSTRING	270
#define	TK_FUNCTION	271
#define	TK_MOD	272
#define	TK_MAIG	273
#define	TK_MEIG	274
#define	TK_DIF	275
#define	TK_IG	276
#define	TK_IF	277
#define	TK_THEN	278
#define	TK_ELSE	279
#define	TK_AND	280
#define	TK_FOR	281
#define	TK_TO	282
#define	TK_DO	283
#define	TK_ARRAY	284
#define	TK_OF	285
#define	TK_PTPT	286
#define	TK_WHILE	287


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int TK_ID;
static const int TK_CINT;
static const int TK_CDOUBLE;
static const int TK_VAR;
static const int TK_PROGRAM;
static const int TK_BEGIN;
static const int TK_END;
static const int TK_MAININ;
static const int TK_MAINFIM;
static const int TK_ATRIB;
static const int TK_WRITELN;
static const int TK_READ;
static const int TK_CSTRING;
static const int TK_FUNCTION;
static const int TK_MOD;
static const int TK_MAIG;
static const int TK_MEIG;
static const int TK_DIF;
static const int TK_IG;
static const int TK_IF;
static const int TK_THEN;
static const int TK_ELSE;
static const int TK_AND;
static const int TK_FOR;
static const int TK_TO;
static const int TK_DO;
static const int TK_ARRAY;
static const int TK_OF;
static const int TK_PTPT;
static const int TK_WHILE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,TK_ID=258
	,TK_CINT=259
	,TK_CDOUBLE=260
	,TK_VAR=261
	,TK_PROGRAM=262
	,TK_BEGIN=263
	,TK_END=264
	,TK_MAININ=265
	,TK_MAINFIM=266
	,TK_ATRIB=267
	,TK_WRITELN=268
	,TK_READ=269
	,TK_CSTRING=270
	,TK_FUNCTION=271
	,TK_MOD=272
	,TK_MAIG=273
	,TK_MEIG=274
	,TK_DIF=275
	,TK_IG=276
	,TK_IF=277
	,TK_THEN=278
	,TK_ELSE=279
	,TK_AND=280
	,TK_FOR=281
	,TK_TO=282
	,TK_DO=283
	,TK_ARRAY=284
	,TK_OF=285
	,TK_PTPT=286
	,TK_WHILE=287


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::TK_ID=258;
const int YY_parse_CLASS::TK_CINT=259;
const int YY_parse_CLASS::TK_CDOUBLE=260;
const int YY_parse_CLASS::TK_VAR=261;
const int YY_parse_CLASS::TK_PROGRAM=262;
const int YY_parse_CLASS::TK_BEGIN=263;
const int YY_parse_CLASS::TK_END=264;
const int YY_parse_CLASS::TK_MAININ=265;
const int YY_parse_CLASS::TK_MAINFIM=266;
const int YY_parse_CLASS::TK_ATRIB=267;
const int YY_parse_CLASS::TK_WRITELN=268;
const int YY_parse_CLASS::TK_READ=269;
const int YY_parse_CLASS::TK_CSTRING=270;
const int YY_parse_CLASS::TK_FUNCTION=271;
const int YY_parse_CLASS::TK_MOD=272;
const int YY_parse_CLASS::TK_MAIG=273;
const int YY_parse_CLASS::TK_MEIG=274;
const int YY_parse_CLASS::TK_DIF=275;
const int YY_parse_CLASS::TK_IG=276;
const int YY_parse_CLASS::TK_IF=277;
const int YY_parse_CLASS::TK_THEN=278;
const int YY_parse_CLASS::TK_ELSE=279;
const int YY_parse_CLASS::TK_AND=280;
const int YY_parse_CLASS::TK_FOR=281;
const int YY_parse_CLASS::TK_TO=282;
const int YY_parse_CLASS::TK_DO=283;
const int YY_parse_CLASS::TK_ARRAY=284;
const int YY_parse_CLASS::TK_OF=285;
const int YY_parse_CLASS::TK_PTPT=286;
const int YY_parse_CLASS::TK_WHILE=287;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		185
#define	YYFLAG		-32768
#define	YYNTBASE	46

#define YYTRANSLATE(x) ((unsigned)(x) <= 287 ? yytranslate[x] : 76)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    40,
    41,    37,    35,    44,    36,     2,    38,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    39,    33,
     2,    34,     2,    45,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    42,     2,    43,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     4,     8,    11,    12,    15,    17,    18,    19,    24,
    29,    33,    34,    38,    40,    43,    50,    54,    56,    60,
    61,    64,    71,    81,    85,    90,    92,    95,    99,   100,
   105,   109,   110,   112,   114,   116,   118,   120,   122,   124,
   134,   144,   154,   164,   170,   176,   182,   188,   192,   198,
   203,   210,   214,   221,   231,   235,   239,   243,   247,   251,
   255,   259,   263,   267,   271,   275,   279,   283,   285,   287,
   289,   291,   296,   304,   306,   309,   314,   318,   320
};

static const short yyrhs[] = {    47,
    48,    61,     0,     7,     3,    39,     0,    49,    48,     0,
     0,     6,    58,     0,    50,     0,     0,     0,    51,    53,
    57,    52,     0,    16,     3,     3,    54,     0,    40,    55,
    41,     0,     0,    56,    39,    55,     0,    56,     0,     3,
    60,     0,    29,     3,    60,    42,     4,    43,     0,     6,
    58,    62,     0,    62,     0,    59,    39,    58,     0,     0,
     3,    60,     0,    29,     3,    60,    42,     4,    43,     0,
    29,     3,    60,    42,     4,    43,    42,     4,    43,     0,
    60,    44,     3,     0,    60,    44,    37,     3,     0,     3,
     0,    37,     3,     0,    10,    57,    11,     0,     0,     8,
    63,    64,     9,     0,    65,    39,    64,     0,     0,    69,
     0,    70,     0,    71,     0,    68,     0,    62,     0,    66,
     0,    67,     0,    26,    75,    12,    72,    39,    75,    33,
    72,    65,     0,    26,    75,    12,    72,    39,    75,    34,
    72,    65,     0,    26,    75,    12,    72,    39,    75,    19,
    72,    65,     0,    26,    75,    12,    72,    39,    75,    18,
    72,    65,     0,    32,    75,    33,    72,    65,     0,    32,
    75,    34,    72,    65,     0,    32,    75,    18,    72,    65,
     0,    32,    75,    19,    72,    65,     0,    22,    72,    65,
     0,    22,    72,    65,    24,    65,     0,    13,    40,    72,
    41,     0,    14,    40,    72,    44,    75,    41,     0,     3,
    12,    72,     0,     3,    42,    72,    43,    12,    72,     0,
     3,    42,    72,    43,    42,    72,    43,    12,    72,     0,
    72,    35,    72,     0,    72,    36,    72,     0,    72,    37,
    72,     0,    72,    17,    72,     0,    72,    38,    72,     0,
    72,    33,    72,     0,    72,    34,    72,     0,    72,    19,
    72,     0,    72,    18,    72,     0,    72,    21,    72,     0,
    72,    20,    72,     0,    72,    25,    72,     0,    40,    72,
    41,     0,    73,     0,     4,     0,     5,     0,    15,     0,
     3,    42,    72,    43,     0,     3,    42,    72,    43,    42,
    72,    43,     0,     3,     0,    45,     3,     0,     3,    40,
    74,    41,     0,    74,    44,    72,     0,    72,     0,     3,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   131,   139,   144,   146,   150,   152,   155,   155,   156,   160,
   167,   169,   173,   185,   188,   198,   211,   214,   219,   221,
   225,   236,   248,   262,   265,   268,   271,   276,   280,   280,
   286,   288,   291,   292,   293,   294,   295,   296,   297,   300,
   320,   340,   360,   382,   398,   414,   430,   450,   452,   457,
   464,   471,   482,   487,   494,   496,   498,   500,   502,   504,
   506,   508,   510,   512,   514,   516,   518,   520,   523,   525,
   527,   529,   545,   563,   565,   567,   592,   597,   603
};

static const char * const yytname[] = {   "$","error","$illegal.","TK_ID","TK_CINT",
"TK_CDOUBLE","TK_VAR","TK_PROGRAM","TK_BEGIN","TK_END","TK_MAININ","TK_MAINFIM",
"TK_ATRIB","TK_WRITELN","TK_READ","TK_CSTRING","TK_FUNCTION","TK_MOD","TK_MAIG",
"TK_MEIG","TK_DIF","TK_IG","TK_IF","TK_THEN","TK_ELSE","TK_AND","TK_FOR","TK_TO",
"TK_DO","TK_ARRAY","TK_OF","TK_PTPT","TK_WHILE","'<'","'>'","'+'","'-'","'*'",
"'/'","';'","'('","')'","'['","']'","','","'@'","S","PROGRAM","DECLS","DECL",
"FUNCTION","@1","@2","CABECALHO","OPC_PARAM","PARAMS","PARAM","CORPO","VARS",
"VAR","IDS","MAIN","BLOCO","@3","CMDS","CMD","CMD_FOR","CMD_WHILE","CMD_IF",
"WRITELN","READ","ATRIB","E","F","EXPRS","NOME_VAR",""
};
#endif

static const short yyr1[] = {     0,
    46,    47,    48,    48,    49,    49,    51,    52,    50,    53,
    54,    54,    55,    55,    56,    56,    57,    57,    58,    58,
    59,    59,    59,    60,    60,    60,    60,    61,    63,    62,
    64,    64,    65,    65,    65,    65,    65,    65,    65,    66,
    66,    66,    66,    67,    67,    67,    67,    68,    68,    69,
    70,    71,    71,    71,    72,    72,    72,    72,    72,    72,
    72,    72,    72,    72,    72,    72,    72,    72,    73,    73,
    73,    73,    73,    73,    73,    73,    74,    74,    75
};

static const short yyr2[] = {     0,
     3,     3,     2,     0,     2,     1,     0,     0,     4,     4,
     3,     0,     3,     1,     2,     6,     3,     1,     3,     0,
     2,     6,     9,     3,     4,     1,     2,     3,     0,     4,
     3,     0,     1,     1,     1,     1,     1,     1,     1,     9,
     9,     9,     9,     5,     5,     5,     5,     3,     5,     4,
     6,     3,     6,     9,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     1,     1,     1,
     1,     4,     7,     1,     2,     4,     3,     1,     1
};

static const short yydefact[] = {     0,
     0,     4,     0,    20,     0,     4,     6,     0,     2,     0,
     0,     5,     0,     0,     1,     3,     0,     0,    26,     0,
    21,     0,    20,    20,    29,     0,    18,     0,     8,    27,
     0,     0,    19,     0,    32,    28,    12,     9,    24,     0,
     0,    17,     0,     0,     0,     0,     0,     0,    37,     0,
     0,    38,    39,    36,    33,    34,    35,     0,    10,    25,
     0,     0,     0,     0,     0,    74,    69,    70,    71,     0,
     0,     0,    68,    79,     0,     0,    30,    32,     0,     0,
     0,    14,    22,    52,     0,     0,     0,     0,     0,     0,
    75,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    48,     0,     0,     0,     0,     0,    31,
    15,     0,    11,     0,     0,     0,    50,     0,    78,     0,
     0,    67,    58,    63,    62,    65,    64,    66,    60,    61,
    55,    56,    57,    59,     0,     0,     0,     0,     0,     0,
     0,    13,     0,     0,     0,     0,    76,     0,    72,    49,
     0,    46,    47,    44,    45,     0,    23,    53,     0,    51,
    77,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    16,     0,    73,     0,     0,     0,     0,    54,    43,    42,
    40,    41,     0,     0,     0
};

static const short yydefgoto[] = {   183,
     2,     5,     6,     7,     8,    38,    18,    59,    81,    82,
    26,    12,    13,    21,    15,    49,    35,    50,    51,    52,
    53,    54,    55,    56,    57,    72,    73,   120,    75
};

static const short yypact[] = {    -2,
     3,     1,   -29,    25,    14,     1,-32768,    47,-32768,    12,
    16,-32768,   -14,    56,-32768,-32768,    39,    56,-32768,    63,
    23,    12,    25,    25,-32768,    59,-32768,    68,-32768,-32768,
    13,   -24,-32768,    85,    65,-32768,    55,-32768,-32768,    96,
    97,-32768,     9,    62,    69,     8,   113,   113,-32768,   110,
    79,-32768,-32768,-32768,-32768,-32768,-32768,    26,-32768,-32768,
    78,     8,     8,     8,     8,    50,-32768,-32768,-32768,     8,
   119,   112,-32768,-32768,   111,    70,-32768,    65,    12,   121,
    94,   100,    98,   337,   156,   264,   134,     8,     8,   289,
-32768,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,   117,     8,     8,     8,     8,     8,-32768,
    23,    12,-32768,    26,   132,    10,-32768,   113,   337,    15,
   183,-32768,-32768,   346,   346,   346,   346,   368,   346,   346,
    43,    43,-32768,-32768,    65,   314,   112,   112,   112,   112,
    54,-32768,   114,     8,     8,   115,-32768,     8,   116,-32768,
   113,-32768,-32768,-32768,-32768,   157,-32768,   337,   210,-32768,
   337,     8,   109,   120,   148,   237,     8,     8,     8,     8,
-32768,     8,-32768,   112,   112,   112,   112,   337,-32768,-32768,
-32768,-32768,   162,   164,-32768
};

static const short yypgoto[] = {-32768,
-32768,   159,-32768,-32768,-32768,-32768,-32768,-32768,    52,-32768,
   161,    34,-32768,   -18,-32768,    51,-32768,   102,   -63,-32768,
-32768,-32768,-32768,-32768,-32768,   -62,-32768,-32768,   -34
};


#define	YYLAST		406


static const short yytable[] = {    84,
    85,    86,    87,    32,     1,     3,     4,    90,   104,     9,
    66,    67,    68,    76,    19,    39,    -7,    41,    22,    31,
    62,   144,    69,    14,    23,   119,   121,    10,    79,   123,
   124,   125,   126,   127,   128,   129,   130,   131,   132,   133,
   134,    28,   136,   137,   138,   139,   140,    70,    20,    40,
    63,   145,    71,    11,    80,   147,    33,    34,   148,    92,
   111,    24,    17,    25,    27,    30,    31,    43,    27,    36,
    37,   150,    25,   152,   153,   154,   155,    44,    45,   102,
   103,   158,   159,   146,    42,   161,    46,   106,   107,    88,
    47,    89,    25,   141,    58,   156,    48,    31,    60,   166,
    61,    64,   108,   109,   174,   175,   176,   177,    65,   178,
   179,   180,   181,   182,    43,    74,   163,    78,    77,    25,
    83,    91,   105,   112,    44,    45,   167,   168,    92,    93,
    94,    95,    96,    46,   113,   143,    97,    47,   114,   115,
   135,   169,   170,    48,    98,    99,   100,   101,   102,   103,
    92,    93,    94,    95,    96,   160,   157,   162,    97,   172,
   164,   184,   171,   185,    16,   142,    98,    99,   100,   101,
   102,   103,    92,    93,    94,    95,    96,   118,    29,   110,
    97,     0,     0,     0,     0,     0,     0,     0,    98,    99,
   100,   101,   102,   103,     0,     0,     0,     0,   116,    92,
    93,    94,    95,    96,     0,     0,     0,    97,     0,     0,
     0,     0,     0,     0,     0,    98,    99,   100,   101,   102,
   103,     0,     0,     0,     0,   149,    92,    93,    94,    95,
    96,     0,     0,     0,    97,     0,     0,     0,     0,     0,
     0,     0,    98,    99,   100,   101,   102,   103,     0,     0,
     0,     0,   165,    92,    93,    94,    95,    96,     0,     0,
     0,    97,     0,     0,     0,     0,     0,     0,     0,    98,
    99,   100,   101,   102,   103,     0,     0,     0,     0,   173,
    92,    93,    94,    95,    96,     0,     0,     0,    97,     0,
     0,     0,     0,     0,     0,     0,    98,    99,   100,   101,
   102,   103,     0,     0,   117,    92,    93,    94,    95,    96,
     0,     0,     0,    97,     0,     0,     0,     0,     0,     0,
     0,    98,    99,   100,   101,   102,   103,     0,     0,   122,
    92,    93,    94,    95,    96,     0,     0,     0,    97,     0,
     0,     0,     0,     0,     0,     0,    98,    99,   100,   101,
   102,   103,   151,    92,    93,    94,    95,    96,     0,     0,
     0,    97,    92,-32768,-32768,-32768,-32768,     0,     0,    98,
    99,   100,   101,   102,   103,     0,     0,     0,-32768,-32768,
   100,   101,   102,   103,    92,    93,    94,    95,    96,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    98,    99,   100,   101,   102,   103
};

static const short yycheck[] = {    62,
    63,    64,    65,    22,     7,     3,     6,    70,    72,    39,
     3,     4,     5,    48,     3,     3,    16,    42,     3,    44,
    12,    12,    15,    10,    39,    88,    89,     3,     3,    92,
    93,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,     3,   105,   106,   107,   108,   109,    40,    37,    37,
    42,    42,    45,    29,    29,    41,    23,    24,    44,    17,
    79,     6,    16,     8,    14,     3,    44,     3,    18,    11,
     3,   135,     8,   137,   138,   139,   140,    13,    14,    37,
    38,   144,   145,   118,    34,   148,    22,    18,    19,    40,
    26,    42,     8,   112,    40,    42,    32,    44,     3,   162,
     4,    40,    33,    34,   167,   168,   169,   170,    40,   172,
   174,   175,   176,   177,     3,     3,   151,    39,     9,     8,
    43,     3,    12,     3,    13,    14,    18,    19,    17,    18,
    19,    20,    21,    22,    41,     4,    25,    26,    39,    42,
    24,    33,    34,    32,    33,    34,    35,    36,    37,    38,
    17,    18,    19,    20,    21,    41,    43,    42,    25,    12,
     4,     0,    43,     0,     6,   114,    33,    34,    35,    36,
    37,    38,    17,    18,    19,    20,    21,    44,    18,    78,
    25,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    33,    34,
    35,    36,    37,    38,    -1,    -1,    -1,    -1,    43,    17,
    18,    19,    20,    21,    -1,    -1,    -1,    25,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    33,    34,    35,    36,    37,
    38,    -1,    -1,    -1,    -1,    43,    17,    18,    19,    20,
    21,    -1,    -1,    -1,    25,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    33,    34,    35,    36,    37,    38,    -1,    -1,
    -1,    -1,    43,    17,    18,    19,    20,    21,    -1,    -1,
    -1,    25,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    33,
    34,    35,    36,    37,    38,    -1,    -1,    -1,    -1,    43,
    17,    18,    19,    20,    21,    -1,    -1,    -1,    25,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    33,    34,    35,    36,
    37,    38,    -1,    -1,    41,    17,    18,    19,    20,    21,
    -1,    -1,    -1,    25,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    33,    34,    35,    36,    37,    38,    -1,    -1,    41,
    17,    18,    19,    20,    21,    -1,    -1,    -1,    25,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    33,    34,    35,    36,
    37,    38,    39,    17,    18,    19,    20,    21,    -1,    -1,
    -1,    25,    17,    18,    19,    20,    21,    -1,    -1,    33,
    34,    35,    36,    37,    38,    -1,    -1,    -1,    33,    34,
    35,    36,    37,    38,    17,    18,    19,    20,    21,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    33,    34,    35,    36,    37,    38
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 132 "trabalho.y"
{
      cout << includes << endl;
      cout << yyvsp[-1].c << endl;
      cout << yyvsp[0].c << endl;
    ;
    break;}
case 2:
#line 140 "trabalho.y"
{ yyval.c = ""; 
            empilha_ts(); ;
    break;}
case 3:
#line 145 "trabalho.y"
{ yyval.c = yyvsp[-1].c + yyvsp[0].c; ;
    break;}
case 4:
#line 147 "trabalho.y"
{ yyval.c = ""; ;
    break;}
case 5:
#line 151 "trabalho.y"
{ yyval.c = yyvsp[0].c; ;
    break;}
case 7:
#line 155 "trabalho.y"
{ empilha_ts(); ;
    break;}
case 8:
#line 155 "trabalho.y"
{ desempilha_ts(); ;
    break;}
case 9:
#line 156 "trabalho.y"
{ yyval.c = yyvsp[-2].c + " {\n" + yyvsp[-1].c + 
                    " return Retorno;\n}\n"; ;
    break;}
case 10:
#line 161 "trabalho.y"
{ 
              Tipo tipo( traduz_nome_tipo_pascal( yyvsp[-2].v ) ); 
              yyval.c = declara_funcao( yyvsp[-1].v, tipo, yyvsp[0].lista_str, yyvsp[0].lista_tipo );
            ;
    break;}
case 11:
#line 168 "trabalho.y"
{ yyval = yyvsp[-1]; ;
    break;}
case 12:
#line 170 "trabalho.y"
{ yyval = Atributos(); ;
    break;}
case 13:
#line 174 "trabalho.y"
{ yyval.c = yyvsp[-2].c + yyvsp[0].c; 
           // Concatenar as listas.
           yyval.lista_tipo = yyvsp[-2].lista_tipo;
           yyval.lista_tipo.insert( yyval.lista_tipo.end(), 
                                 yyvsp[0].lista_tipo.begin(),  
                                 yyvsp[0].lista_tipo.end() ); 
           yyval.lista_str = yyvsp[-2].lista_str;
           yyval.lista_str.insert( yyval.lista_str.end(), 
                                yyvsp[0].lista_str.begin(),  
                                yyvsp[0].lista_str.end() ); 
         ;
    break;}
case 15:
#line 189 "trabalho.y"
{
        Tipo tipo = Tipo( traduz_nome_tipo_pascal( yyvsp[-1].v ) ); 
        
        yyval = Atributos();
        yyval.lista_str = yyvsp[0].lista_str;
        
        for( int i = 0; i < yyvsp[0].lista_str.size(); i ++ ) 
          yyval.lista_tipo.push_back( tipo );
      ;
    break;}
case 16:
#line 199 "trabalho.y"
{
        Tipo tipo = Tipo( traduz_nome_tipo_pascal( yyvsp[-4].v ), 
                          toInt( yyvsp[-1].v ) );
        
        yyval = Atributos();
        yyval.lista_str = yyvsp[-3].lista_str;
        
        for( int i = 0; i < yyvsp[-3].lista_str.size(); i ++ ) 
          yyval.lista_tipo.push_back( tipo );
      ;
    break;}
case 17:
#line 212 "trabalho.y"
{ yyval.c = declara_variavel( "Retorno", consulta_ts( "Retorno" ) ) + ";\n" +
                 yyvsp[-1].c + yyvsp[0].c; ;
    break;}
case 18:
#line 215 "trabalho.y"
{ yyval.c = declara_variavel( "Retorno", consulta_ts( "Retorno" ) ) + ";\n" +
                 yyvsp[0].c; ;
    break;}
case 19:
#line 220 "trabalho.y"
{ yyval.c = yyvsp[-2].c + yyvsp[0].c; ;
    break;}
case 20:
#line 222 "trabalho.y"
{ yyval = Atributos(); ;
    break;}
case 21:
#line 226 "trabalho.y"
{
        Tipo tipo = Tipo( traduz_nome_tipo_pascal( yyvsp[-1].v ) ); 
        
        yyval = Atributos();
        
        for( int i = 0; i < yyvsp[0].lista_str.size(); i ++ ) {
          yyval.c += declara_variavel( yyvsp[0].lista_str[i], tipo ) + ";\n";
          insere_var_ts( yyvsp[0].lista_str[i], tipo );
        }
      ;
    break;}
case 22:
#line 237 "trabalho.y"
{
        Tipo tipo = Tipo( traduz_nome_tipo_pascal( yyvsp[-4].v ), 
                          toInt( yyvsp[-1].v ) );
        
        yyval = Atributos();
        
        for( int i = 0; i < yyvsp[-3].lista_str.size(); i ++ ) {
          yyval.c += declara_variavel( yyvsp[-3].lista_str[i], tipo ) + ";\n";
          insere_var_ts( yyvsp[-3].lista_str[i], tipo );
        }
      ;
    break;}
case 23:
#line 249 "trabalho.y"
{
        Tipo tipo = Tipo( traduz_nome_tipo_pascal( yyvsp[-7].v ), 
                          toInt( yyvsp[-4].v ), toInt( yyvsp[-1].v ) );
        
        yyval = Atributos();
        
        for( int i = 0; i < yyvsp[-6].lista_str.size(); i ++ ) {
          yyval.c += declara_variavel( yyvsp[-6].lista_str[i], tipo ) + ";\n";
          insere_var_ts( yyvsp[-6].lista_str[i], tipo );
        }
      ;
    break;}
case 24:
#line 263 "trabalho.y"
{ yyval  = yyvsp[-2];
        yyval.lista_str.push_back( yyvsp[0].v ); ;
    break;}
case 25:
#line 266 "trabalho.y"
{ yyval  = yyvsp[-3];
        yyval.lista_str.push_back( yyvsp[-1].v + yyvsp[0].v); ;
    break;}
case 26:
#line 269 "trabalho.y"
{ yyval = Atributos();
        yyval.lista_str.push_back( yyvsp[0].v ); ;
    break;}
case 27:
#line 272 "trabalho.y"
{ yyval = Atributos();
        yyval.lista_str.push_back( yyvsp[-1].v + yyvsp[0].v); ;
    break;}
case 28:
#line 277 "trabalho.y"
{ yyval.c = "int main() { \n" + yyvsp[-1].c + "}\n"; ;
    break;}
case 29:
#line 280 "trabalho.y"
{ var_temp.push_back( "" );;
    break;}
case 30:
#line 281 "trabalho.y"
{ string vars = var_temp[var_temp.size()-1];
          var_temp.pop_back();
          yyval.c = vars + yyvsp[-1].c; ;
    break;}
case 31:
#line 287 "trabalho.y"
{ yyval.c = yyvsp[-2].c + yyvsp[0].c; ;
    break;}
case 32:
#line 288 "trabalho.y"
{ yyval.c = ""; ;
    break;}
case 40:
#line 301 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-7].t.tipo_base );
            string label_teste = gera_label( "teste_for" );
            string label_fim = gera_label( "fim_for" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  yyvsp[-5].c + yyvsp[-1].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-5].v + ";\n" +
                    "  " + var_fim + " = " + yyvsp[-1].v + ";\n" +
                    label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-7].v + " >= " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-7].v + " + 1;\n" +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 41:
#line 321 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-7].t.tipo_base );
            string label_teste = gera_label( "teste_for" );
            string label_fim = gera_label( "fim_for" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  yyvsp[-5].c + yyvsp[-1].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-5].v + ";\n" +
                    "  " + var_fim + " = " + yyvsp[-1].v + ";\n" +
                    label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-7].v + " <= " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-7].v + " - 1;\n" +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 42:
#line 341 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-7].t.tipo_base );
            string label_teste = gera_label( "teste_for" );
            string label_fim = gera_label( "fim_for" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  yyvsp[-5].c + yyvsp[-1].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-5].v + ";\n" +
                    "  " + var_fim + " = " + yyvsp[-1].v + ";\n" +
                    label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-7].v + " > " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-7].v + " + 1;\n" +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 43:
#line 361 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-7].t.tipo_base );
            string label_teste = gera_label( "teste_for" );
            string label_fim = gera_label( "fim_for" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  yyvsp[-5].c + yyvsp[-1].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-5].v + ";\n" +
                    "  " + var_fim + " = " + yyvsp[-1].v + ";\n" +
                    label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-7].v + " < " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c +
                    "  " + yyvsp[-7].v + " = " + yyvsp[-7].v + " - 1;\n" +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 44:
#line 383 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-3].t.tipo_base );
            string label_teste = gera_label( "teste_while" );
            string label_fim = gera_label( "fim_while" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  var_fim + " = " + yyvsp[-1].v + ";\n" + label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-3].v + " >= " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c  +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 45:
#line 399 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-3].t.tipo_base );
            string label_teste = gera_label( "teste_while" );
            string label_fim = gera_label( "fim_while" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  var_fim + " = " + yyvsp[-1].v + ";\n" + label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-3].v + " <= " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c  +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 46:
#line 415 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-3].t.tipo_base );
            string label_teste = gera_label( "teste_while" );
            string label_fim = gera_label( "fim_while" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  var_fim + " = " + yyvsp[-1].v + ";\n" + label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-3].v + " < " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c  +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 47:
#line 431 "trabalho.y"
{ 
            string var_fim = gera_nome_var_temp( yyvsp[-3].t.tipo_base );
            string label_teste = gera_label( "teste_while" );
            string label_fim = gera_label( "fim_while" );
            string condicao = gera_nome_var_temp( "b" );
          
            // Falta verificar os tipos... perde ponto se não o fizer.
            yyval.c =  var_fim + " = " + yyvsp[-1].v + ";\n" + label_teste + ":;\n" +
                    "  " +condicao+" = "+yyvsp[-3].v + " > " + var_fim + ";\n" + 
                    "  " + "if( " + condicao + " ) goto " + label_fim + 
                    ";\n" +
                    yyvsp[0].c  +
                    "  goto " + label_teste + ";\n" +
                    label_fim + ":;\n";  
          ;
    break;}
case 48:
#line 451 "trabalho.y"
{ yyval = gera_codigo_if( yyvsp[-1], yyvsp[0].c, "" ); ;
    break;}
case 49:
#line 453 "trabalho.y"
{ yyval = gera_codigo_if( yyvsp[-3], yyvsp[-2].c, yyvsp[0].c ); ;
    break;}
case 50:
#line 458 "trabalho.y"
{ yyval.c = yyvsp[-1].c + 
                   "  cout << " + yyvsp[-1].v + ";\n"
                   "  cout << endl;\n";
          ;
    break;}
case 51:
#line 465 "trabalho.y"
{	yyval.c = yyvsp[-3].c +
				" cout << " + yyvsp[-3].v + ";\n" +
				" cin >> " +  yyvsp[-1].v + ";\n";
		;
    break;}
case 52:
#line 472 "trabalho.y"
{ // Falta verificar se pode atribuir (perde ponto se não fizer).
          yyvsp[-2].t = consulta_ts( yyvsp[-2].v ) ;
          
          if( yyvsp[-2].t.tipo_base == "s" ) 
            yyval.c = yyvsp[0].c + "  strncpy( " + yyvsp[-2].v + ", " + yyvsp[0].v + ", 256 );\n";
          else
            yyval.c = yyvsp[0].c + "  " + yyvsp[-2].v + " = " + yyvsp[0].v + ";\n"; 
            
          debug( "ATRIB : TK_ID TK_ATRIB E ';'", yyval );
        ;
    break;}
case 53:
#line 483 "trabalho.y"
{ // Falta testar: tipo, limite do array, e se a variável existe
          yyval.c = yyvsp[-3].c + yyvsp[0].c +
                 "  " + yyvsp[-5].v + "[" + yyvsp[-3].v + "] = " + yyvsp[0].v + ";\n";
        ;
    break;}
case 54:
#line 488 "trabalho.y"
{ // Falta testar: tipo, limite do array, e se a variável existe
          yyval.c = yyvsp[-6].c + yyvsp[-3].c + yyvsp[0].c +
                 "  " + yyvsp[-8].v + "[" + yyvsp[-6].v + "][" + yyvsp[-3].v + "] = " + yyvsp[0].v + ";\n";
        ;
    break;}
case 55:
#line 495 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "+", yyvsp[0] ); ;
    break;}
case 56:
#line 497 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "-", yyvsp[0] ); ;
    break;}
case 57:
#line 499 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "*", yyvsp[0] ); ;
    break;}
case 58:
#line 501 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "%", yyvsp[0] ); ;
    break;}
case 59:
#line 503 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "/", yyvsp[0] ); ;
    break;}
case 60:
#line 505 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "<", yyvsp[0] ); ;
    break;}
case 61:
#line 507 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], ">", yyvsp[0] ); ;
    break;}
case 62:
#line 509 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "<=", yyvsp[0] ); ;
    break;}
case 63:
#line 511 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], ">=", yyvsp[0] ); ;
    break;}
case 64:
#line 513 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "==", yyvsp[0] ); ;
    break;}
case 65:
#line 515 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "!=", yyvsp[0] ); ;
    break;}
case 66:
#line 517 "trabalho.y"
{ yyval = gera_codigo_operador( yyvsp[-2], "&&", yyvsp[0] ); ;
    break;}
case 67:
#line 519 "trabalho.y"
{ yyval = yyvsp[-1]; ;
    break;}
case 69:
#line 524 "trabalho.y"
{ yyval.v = yyvsp[0].v; yyval.t = Tipo( "i" ); yyval.c = yyvsp[0].c; ;
    break;}
case 70:
#line 526 "trabalho.y"
{ yyval.v = yyvsp[0].v; yyval.t = Tipo( "d" ); yyval.c = yyvsp[0].c; ;
    break;}
case 71:
#line 528 "trabalho.y"
{ yyval.v = yyvsp[0].v; yyval.t = Tipo( "s" ); yyval.c = yyvsp[0].c; ;
    break;}
case 72:
#line 530 "trabalho.y"
{ 
      Tipo tipoArray = consulta_ts( yyvsp[-3].v );
      yyval.t = Tipo( tipoArray.tipo_base );
      if( tipoArray.ndim != 1 )
        erro( "Variável " + yyvsp[-3].v + " não é array de uma dimensão" );
        
      if( yyvsp[-1].t.ndim != 0 || yyvsp[-1].t.tipo_base != "i" )
        erro( "Indice de array deve ser integer de zero dimensão: " +
              yyvsp[-1].t.tipo_base + "/" + toString( yyvsp[-1].t.ndim ) );
        
      yyval.v = gera_nome_var_temp( yyval.t.tipo_base );
      yyval.c = yyvsp[-1].c +
             gera_teste_limite_array( yyvsp[-1].v, tipoArray ) +   
             "  " + yyval.v + " = " + yyvsp[-3].v + "[" + yyvsp[-1].v + "];\n";
    ;
    break;}
case 73:
#line 546 "trabalho.y"
{
      // Implementar: vai criar uma temporaria int para o índice e 
      // outra do tipoBase do array para o valor recuperado.
      Tipo tipoArray = consulta_ts( yyvsp[-6].v );
      yyval.t = Tipo( tipoArray.tipo_base );
      if( tipoArray.ndim != 2 )
        erro( "Variável " + yyvsp[-6].v + " não é array de duas dimensões" );
        
      if( yyvsp[-4].t.ndim != 0 || yyvsp[-4].t.tipo_base != "i" || yyvsp[-1].t.ndim != 0 || yyvsp[-1].t.tipo_base != "i" )
        erro( "Indice de array deve ser integer de zero dimensão: " +
              yyvsp[-4].t.tipo_base + "/" + toString( yyvsp[-4].t.ndim ) );
        
      yyval.v = gera_nome_var_temp( yyval.t.tipo_base );
      yyval.c = yyvsp[-4].c +
             gera_teste_limite_array( yyvsp[-4].v, yyvsp[-1].v, tipoArray ) +   
             "  " + yyval.v + " = " + yyvsp[-6].v + "[" + yyvsp[-4].v + "][" + yyvsp[-1].v + "];\n";    	
    ;
    break;}
case 74:
#line 564 "trabalho.y"
{ yyval.v = yyvsp[0].v; yyval.t = consulta_ts( yyvsp[0].v ); yyval.c = yyvsp[0].c; ;
    break;}
case 75:
#line 566 "trabalho.y"
{ yyval.v = "&" + yyvsp[0].v; yyval.t = consulta_ts( yyvsp[0].v ); yyval.c = yyvsp[-1].c + yyvsp[0].c; ;
    break;}
case 76:
#line 568 "trabalho.y"
{ yyval.t = Tipo( "i" ); // consulta_ts( $1.v );
    // Falta verficar o tipo da função e os parametros.
      Tipo funcao = consulta_ts(yyvsp[-3].v);
      if(funcao.params.size()!= yyvsp[-1].lista_str.size())
      	erro( "Numero de parametros incorretos na função: " + yyvsp[-3].v + 
      		"\n" + " " +"Numero de parametros necessários: " + toString(consulta_ts(yyvsp[-3].v).params.size()) + 
      		"\n" + " " + "Número de parâmetros fornecidos: " + toString(yyvsp[-1].lista_str.size()));

	  for(int i = 0; i< funcao.params.size() ; i++){
      	if(!verifica_tipo(funcao.params[i],yyvsp[-1].lista_str[i])){
		      		erro( "Tipos dos parâmetros diferentes na função: " + yyvsp[-3].v );
  		}
  	  }
      yyval.v = gera_nome_var_temp( yyval.t.tipo_base ); 
      yyval.c = yyvsp[-1].c + "  " + yyval.v + " = " + yyvsp[-3].v + "( ";
      
      for( int i = 0; i < yyvsp[-1].lista_str.size() - 1; i++ )
        yyval.c += yyvsp[-1].lista_str[i] + ", ";
        
      yyval.c += yyvsp[-1].lista_str[yyvsp[-1].lista_str.size()-1] + " );\n"; 
    ;
    break;}
case 77:
#line 593 "trabalho.y"
{ yyval = Atributos();
          yyval.c = yyvsp[-2].c + yyvsp[0].c;
          yyval.lista_str = yyvsp[-2].lista_str;
          yyval.lista_str.push_back( yyvsp[0].v ); ;
    break;}
case 78:
#line 598 "trabalho.y"
{ yyval = Atributos();
          yyval.c = yyvsp[0].c;
          yyval.lista_str.push_back( yyvsp[0].v ); ;
    break;}
case 79:
#line 604 "trabalho.y"
{ yyval.v = yyvsp[0].v; yyval.t = consulta_ts( yyvsp[0].v ); yyval.c = yyvsp[0].c; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 607 "trabalho.y"

int nlinha = 1;

#include "lex.yy.c"

int yyparse();

void debug( string producao, Atributos atr ) {
/*
  cerr << "Debug: " << producao << endl;
  cerr << "  t: " << atr.t << endl;
  cerr << "  v: " << atr.v << endl;
  cerr << "  c: " << atr.c << endl;
*/ 
}

void yyerror( const char* st )
{
  printf( "%s", st );
  printf( "Linha: %d, \"%s\"\n", nlinha, yytext );
}

void erro( string msg ) {
  cerr << "Erro: " << msg << endl; 
  fprintf( stderr, "Linha: %d, [%s]\n", nlinha, yytext );
  exit(1);
}

void inicializa_operadores() {
  // Resultados para o operador "+"
  tipo_opr["i+i"] = "i";
  tipo_opr["i+d"] = "d";
  tipo_opr["d+i"] = "d";
  tipo_opr["d+d"] = "d";
  tipo_opr["s+s"] = "s";
  tipo_opr["c+s"] = "s";
  tipo_opr["s+c"] = "s";
  tipo_opr["c+c"] = "s";
 
  // Resultados para o operador "-"
  tipo_opr["i-i"] = "i";
  tipo_opr["i-d"] = "d";
  tipo_opr["d-i"] = "d";
  tipo_opr["d-d"] = "d";
  
  // Resultados para o operador "*"
  tipo_opr["i*i"] = "i";
  tipo_opr["i*d"] = "d";
  tipo_opr["d*i"] = "d";
  tipo_opr["d*d"] = "d";
  
  // Resultados para o operador "/"
  tipo_opr["i/i"] = "d";
  tipo_opr["i/d"] = "d";
  tipo_opr["d/i"] = "d";
  tipo_opr["d/d"] = "d";
  
  // Resultados para o operador "%"
  tipo_opr["i%i"] = "i";
  
  // Resultados para o operador "<"
  tipo_opr["i<i"] = "b";
  tipo_opr["i<d"] = "b";
  tipo_opr["d<i"] = "b";
  tipo_opr["d<d"] = "b";
  tipo_opr["c<c"] = "b";
  tipo_opr["i<c"] = "b";
  tipo_opr["c<i"] = "b";
  tipo_opr["c<s"] = "b";
  tipo_opr["s<c"] = "b";
  tipo_opr["s<s"] = "b";

  // Resultados para o operador "And"
  tipo_opr["b&&b"] = "b";
  
  // Resultados para o operador "="
  tipo_opr["i==i"] = "b";
  tipo_opr["i==d"] = "b";
  tipo_opr["d==i"] = "b";
  tipo_opr["d==d"] = "b";
  tipo_opr["s==s"] = "b";
}

// Uma tabela de símbolos para cada escopo
vector< map< string, Tipo > > ts;

void empilha_ts() {
  map< string, Tipo > novo;
  ts.push_back( novo );
}

void desempilha_ts() {
  ts.pop_back();
}

Tipo consulta_ts( string nome_var ) {
  for( int i = ts.size()-1; i >= 0; i-- )
    if( ts[i].find( nome_var ) != ts[i].end() )
      return ts[i][ nome_var ];
    
  erro( "Variável não declarada: " + nome_var );
  
  return Tipo();
}

void insere_var_ts( string nome_var, Tipo tipo ) {
  if( ts[ts.size()-1].find( nome_var ) != ts[ts.size()-1].end() )
    erro( "Variável já declarada: " + nome_var + 
          " (" + ts[ts.size()-1][ nome_var ].tipo_base + ")" );
    
  ts[ts.size()-1][ nome_var ] = tipo;
}

void insere_funcao_ts( string nome_func, 
                       Tipo retorno, vector<Tipo> params ) {
  if( ts[ts.size()-2].find( nome_func ) != ts[ts.size()-2].end() )
    erro( "Função já declarada: " + nome_func );
    
  ts[ts.size()-2][ nome_func ] = Tipo( retorno, params );
}

string toString( int n ) {
  char buff[100];
  
  sprintf( buff, "%d", n ); 
  
  return buff;
}

int toInt( string valor ) {
  int aux = -1;
  
  if( sscanf( valor.c_str(), "%d", &aux ) != 1 )
    erro( "Numero inválido: " + valor );
  
  return aux;
}
string gera_nome_var_temp( string tipo ) {
  static int n = 0;
  string nome = "t" + tipo + "_" + toString( ++n );
  
  var_temp[var_temp.size()-1] += declara_variavel( nome, Tipo( tipo ) ) + ";\n";
  insere_var_ts(nome,Tipo(tipo));
  return nome;
}

string gera_label( string tipo ) {
  static int n = 0;
  string nome = "l_" + tipo + "_" + toString( ++n );
  
  return nome;
}

Tipo tipo_resultado( Tipo t1, string opr, Tipo t3 ) {
  if( t1.ndim == 0 && t3.ndim == 0 ) {
    string aux = tipo_opr[ t1.tipo_base + opr + t3.tipo_base ];
  
    if( aux == "" ) 
      erro( "O operador " + opr + " não está definido para os tipos '" +
            t1.tipo_base + "' e '" + t3.tipo_base + "'.");
  
    return Tipo( aux );
  }
  else { // Testes para os operadores de comparacao de array
    return Tipo();
  }  
} 

Atributos gera_codigo_operador( Atributos s1, string opr, Atributos s3 ) {
  Atributos ss;
  
  ss.t = tipo_resultado( s1.t, opr, s3.t );
  ss.v = gera_nome_var_temp( ss.t.tipo_base );
  
  if( s1.t.tipo_base == "s" && s3.t.tipo_base == "s" ){ 
    // falta testar se é o operador "+"
    if(opr=="+"){
		ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
		       "  strncpy( " + ss.v + ", " + s1.v + ", 256 );\n" +
		       "  strncat( " + ss.v + ", " + s3.v + ", 256 );\n";
  	}
  	if(opr=="<"){
		ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
		       "if(strncmp( " + s1.v + ", " + s3.v + ", 256 )<0)	" + ss.v + "=true;\n" +
		       "else 	" + ss.v + "=false;\n";
  	}
  	if(opr==">"){
		ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
		       "if(strncmp( " + s1.v + ", " + s3.v + ", 256 )>0)	" + ss.v + "=true;\n" +
		       "else 	" + ss.v + "=false;\n";
  	}
  	if(opr=="=="){
		ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
		       "if(strncmp( " + s1.v + ", " + s3.v + ", 256 )==0)	" + ss.v + "=true;\n" +
		       "else 	" + ss.v + "=false;\n";
  	}
  	if(opr=="!="){
		ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
		       "if(strncmp( " + s1.v + ", " + s3.v + ", 256 )!=0)	" + ss.v + "=true;\n" +
		       "else 	" + ss.v + "=false;\n";
  	}
  }
  else if( s1.t.tipo_base == "s" && s3.t.tipo_base == "c" ) 
    ;
  else if( s1.t.tipo_base == "c" && s3.t.tipo_base == "s" ) 
    ;
  else
    ss.c = s1.c + s3.c + // Codigo das expressões dos filhos da arvore.
           "  " + ss.v + " = " + s1.v + " " + opr + " " + s3.v + ";\n"; 
  
  debug( "E: E " + opr + " E", ss );
  return ss;
}

Atributos gera_codigo_if( Atributos expr, string cmd_then, string cmd_else ) {
  Atributos ss;
  string label_else = gera_label( "else" );
  string label_end = gera_label( "end" );
  
  ss.c = expr.c + 
         "  " + expr.v + " = !" + expr.v + ";\n\n" +
         "  if( " + expr.v + " ) goto " + label_else + ";\n" +
         cmd_then +
         "  goto " + label_end + ";\n" +
         label_else + ":;\n" +
         cmd_else +
         label_end + ":;\n";
         
  return ss;       
}


string traduz_nome_tipo_pascal( string tipo_pascal ) {
  // No caso do Pascal, a comparacao deveria ser case-insensitive
  
  if( tipo_pascal == "intr" )
    return "i";
  else if( tipo_pascal == "booleano" )
    return "b";
  else if( tipo_pascal == "real" )
    return "d";  
  else if( tipo_pascal == "caracter" )
    return "c";  
  else if( tipo_pascal == "str" )
    return "s";  
  else 
    erro( "Tipo inválido: " + tipo_pascal );
}

map<string, string> inicializaMapEmC() {
  map<string, string> aux;
  aux["i"] = "int ";
  aux["b"] = "int ";
  aux["d"] = "double ";
  aux["c"] = "char ";
  aux["s"] = "char ";
  return aux;
}

string declara_funcao( string nome, Tipo tipo, 
                       vector<string> nomes, vector<Tipo> tipos ) {
  static map<string, string> em_C = inicializaMapEmC();
  
  if( em_C[ tipo.tipo_base ] == "" ) 
    erro( "Tipo inválido: " + tipo.tipo_base );
    
  insere_var_ts( "Retorno", tipo );  
    
  if( nomes.size() != tipos.size() )
    erro( "Bug no compilador! Nomes e tipos de parametros diferentes." );
  insere_funcao_ts(nome, tipo, tipos);    
  string aux = "";
  
  for( int i = 0; i < nomes.size(); i++ ) {
  	aux += declara_variavel( nomes[i], tipos[i] ) + 
           (i == nomes.size()-1 ? " " : ", ");  
    if(nomes[i][0]=='&'||nomes[i][0]=='*')	nomes[i]=nomes[i].substr(1,nomes[i].length());
    insere_var_ts( nomes[i], tipos[i] );  
  }
      
  return em_C[ tipo.tipo_base ] + " " + nome + "(" + aux + ")";
}

string declara_variavel( string nome, Tipo tipo ) {
  static map<string, string> em_C = inicializaMapEmC();
  
  if( em_C[ tipo.tipo_base ] == "" ) 
    erro( "Tipo inválido: " + tipo.tipo_base );
    
  string indice;
   
  switch( tipo.ndim ) {
    case 0: indice = (tipo.tipo_base == "s" ? "[256]" : "");
            break;
              
    case 1: indice = "[" + toString( 
                  (tipo.tamanho1[0]) *  
                  (tipo.tipo_base == "s" ? 256 : 1)
                ) + "]";
            break; 
            
    case 2:
    		indice = "[" + toString( 
                  (tipo.tamanho1[0]) *  
                  (tipo.tipo_base == "s" ? 256 : 1)
                ) + "]" + "[" + toString( 
                  (tipo.tamanho2[0]) *  
                  (tipo.tipo_base == "s" ? 256 : 1)
                ) + "]";
            break;
    
    default:
       erro( "Bug muito sério..." );
  } 
  
  return em_C[ tipo.tipo_base ] + nome + indice;
}

string gera_teste_limite_array( string indice_1, Tipo tipoArray ) {
  string var_teste_inicio = gera_nome_var_temp( "b" );
  string var_teste_fim = gera_nome_var_temp( "b" );
  string var_teste = gera_nome_var_temp( "b" );
  string label_end = gera_label( "limite_array_ok" );

  string codigo = "  " + var_teste_inicio + " = " + indice_1 + " >= 0;\n" +
                  "  " + var_teste_fim + " = " + indice_1 + " <= " +
                  toString( tipoArray.tamanho1[0] ) + ";\n" +
                  "  " + var_teste + " = " + var_teste_inicio + " && " + 
                                             var_teste_fim + ";\n";
                                             
  codigo += "  if( " + var_teste + " ) goto " + label_end + ";\n" +
          "    printf( \"Limite de array ultrapassado: %d <= %d <= %d\", 0 ," + indice_1 + ", " +
               toString( tipoArray.tamanho1[0] ) + " );\n" +
               "  cout << endl;\n" + 
               "  exit( 1 );\n" + 
            "  " + label_end + ":;\n";
  
  return codigo;
}

string gera_teste_limite_array( string indice_1, string indice_2, Tipo tipoArray ){
  string var_teste_inicio = gera_nome_var_temp( "b" );
  string var_teste_fim = gera_nome_var_temp( "b" );
  string var_teste = gera_nome_var_temp( "b" );
  string label_end = gera_label( "limite_array_ok" );

  string codigo = "  " + var_teste_inicio + " = " + indice_1 + " >= 0;\n" +
                  "  " + var_teste_fim + " = " + indice_1 + " <= " +
                  toString( tipoArray.tamanho1[0] ) + ";\n" +
                  "  " + var_teste + " = " + var_teste_inicio + " && " + 
                                             var_teste_fim + ";\n";
                                             
  codigo += "  if( " + var_teste + " ) goto " + label_end + ";\n" +
          "    printf( \"Limite de array ultrapassado: %d <= %d <= %d\", 0 ," + indice_1 + ", " +
               toString( tipoArray.tamanho1[0] ) + " );\n" +
               "  cout << endl;\n" + 
               "  exit( 1 );\n";

  codigo += "  " + var_teste_inicio + " = " + indice_1 + " >= 0;\n" +
	          "  " + var_teste_fim + " = " + indice_1 + " <= " +
	          toString( tipoArray.tamanho2[0] ) + ";\n" +
	          "  " + var_teste + " = " + var_teste_inicio + " && " + 
	                                     var_teste_fim + ";\n";
  
  codigo += "  if( " + var_teste + " ) goto " + label_end + ";\n" +
          "    printf( \"Limite de array ultrapassado: %d <= %d <= %d\", 0 ," + indice_1 + ", " +
               toString( tipoArray.tamanho2[0] ) + " );\n" +
               "  cout << endl;\n" + 
               "  exit( 1 );\n" + 
            "  " + label_end + ":;\n";
  return codigo;
}

int verifica_tipo(Tipo var1, string var2){ //verificar tipos aqui
	if(var2[0]=='&'||var2[0]=='*')	var2=var2.substr(1,var2.length());
	if(var1.tipo_base=="i"){
  		if(!isdigit(var2[0])){
  			if(consulta_ts(var2).tipo_base!="i")
	      		return 0;
  		}
  		else{
  			if(!stoi(var2))
  				return 0;		
  		}
  	}
  	if(var1.tipo_base=="d"){
  		if(!isdigit(var2[0])){
  			if(consulta_ts(var2).tipo_base!="d")
      			return 0;
      	}
  		else{
  			if(!stod(var2))
  				return 0;
  		}
  	}
  	return 1;
}

int main( int argc, char* argv[] )
{
  inicializa_operadores();
  yyparse();
}
